export const PAYLOADS_DATA = [
  {
    id: 1,
    title: "HTTP",
    method: "WS FNF Tunnel BD",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: video.pscp.tv[crlf]Expect: 100-continue[crlf][crlf][split]CF-RAY / HTTP/1.1[crlf]Host: [cf][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "partner-stream.twitter.com:8880",
    stars: 5,
  },
  {
    id: 2,
    title: "HTTP",
    method: "WebSocket Split",
    payload: "GET / HTTP/1.1 [lf]Host: [host][crlf]User-Agent: [crlf]Connection: upgrade[lf]Upgrade: Websocket[lf][lf][split]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "googleapis.com",
    stars: 4,
  },
  {
    id: 3,
    title: "HTTP",
    method: "Dual GET",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [host][crlf][crlf]GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:[host_port][crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 5,
  },
  {
    id: 4,
    title: "HTTP",
    method: "POST",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: web.googel.com[crlf][crlf]POST / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:cloudflare.com [crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:8080",
    sni: "content-autofill.googleapis.com",
    stars: 5,
  },
  {
    id: 5,
    title: "HTTP",
    method: "PATCH",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: web.googel.com[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:www.snapchat.com [crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "googleapis.com",
    stars: 5,
  },
  {
    id: 6,
    title: "HTTP",
    method: "ACL",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: web.googel.com[crlf][crlf]ACL / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:www.facebook.com [crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 5,
  },
  {
    id: 7,
    title: "HTTP",
    method: "CONNECT",
    payload: "CONNECT / HTTP/1.1[crlf]Host: [host][crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf]x-firewallfalcon-mode: true[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "content-autofill.googleapis.com",
    stars: 5,
  },
  {
    id: 8,
    title: "HTTP",
    method: "Split + PATCH",
    payload: "PATCH / [split]HTTP/1.1 [lf]Host: [host][crlf]Connection:[lf]Upgrade: Websocket[lf][lf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "googleapis.com",
    stars: 4,
  },
  {
    id: 9,
    title: "HTTP",
    method: "Split + PATCH",
    payload: "PATCH / HTTP/1.1[split][crlf]Host: [host][crlf]Connection:[lf]Upgrade: Websocket[lf][lf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 4,
  },
  {
    id: 10,
    title: "HTTP",
    method: "SSH",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:22",
    sni: "content-autofill.googleapis.com",
    stars: 4,
  },
  {
    id: 11,
    title: "HTTP",
    method: "Slowed DNS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:22",
    sni: "googleapis.com",
    stars: 4,
  },
  {
    id: 12,
    title: "HTTP",
    method: "ACL Split",
    payload: "ACL / [split]HTTP/1.1 [lf]Host: [rlb][lf]Upgrade: Websocket[lf][lf]",
    proxy: "dev-guest-cf.pscp.tv:8880",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 5,
  },
  {
    id: 13,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: googleapis.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "googleapis.com",
    stars: 5,
  },
  {
    id: 14,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: v9x6qb-launches.appsflyersdk.com[crlf][crlf]GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:v9x6qb-launches.appsflyersdk.com [crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 5,
  },
  {
    id: 15,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: content-autofill.googleapis.com[crlf]Upgrade: websocket[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "content-autofill.googleapis.com",
    stars: 5,
  },
  {
    id: 16,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "googleapis.com",
    stars: 5,
  },
  {
    id: 17,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [host][crlf][crlf]GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:[host][crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "v9x6qb-launches.appsflyersdk.com",
    stars: 5,
  },
  {
    id: 18,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: web.facebook.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "web.facebook.com",
    stars: 5,
  },
  {
    id: 19,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET /cdn-cgi/trace HTTP/1.1[crlf]Host: web.facebook.com[crlf][crlf]GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade:websocket:web.facebook.com [crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "help.facebook.com",
    stars: 5,
  },
  {
    id: 20,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "m.facebook.com",
    stars: 5,
  },
  {
    id: 21,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: web.whatsapp.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "web.whatsapp.com",
    stars: 5,
  },
  {
    id: 22,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "m.whatsapp.com",
    stars: 5,
  },
  {
    id: 23,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: web.telegram.org[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "web.telegram.org",
    stars: 5,
  },
  {
    id: 24,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "m.telegram.org",
    stars: 5,
  },
  {
    id: 25,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: www.tiktok.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "www.tiktok.com",
    stars: 5,
  },
  {
    id: 26,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "m.tiktok.com",
    stars: 5,
  },
  {
    id: 27,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: assets.twitch.tv[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "assets.twitch.tv",
    stars: 5,
  },
  {
    id: 28,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: cdn.discordapp.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "cdn.discordapp.com",
    stars: 5,
  },
  {
    id: 29,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "api.discordapp.com",
    stars: 5,
  },
  {
    id: 30,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: web.cloudflare.com[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "web.cloudflare.com",
    stars: 5,
  },
  {
    id: 31,
    title: "HTTPS SSL TLS",
    method: "SSL TLS",
    payload: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
    proxy: "dev-guest-cf.pscp.tv:443",
    sni: "help.cloudflare.com",
    stars: 5,
  },
];

export const PROXIES_DATA = [
  // video-cf.twimg.com
  { host: "video-cf.twimg.com", port: 8080, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "video-cf.twimg.com", port: 8880, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "video-cf.twimg.com", port: 2086, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "video-cf.twimg.com", port: 443, type: "SSL", online: true, provider: "Twitter/CDN" },
  { host: "video-cf.twimg.com", port: 80, type: "HTTP", online: true, provider: "Twitter/CDN" },
  // crazygames.ro
  { host: "crazygames.ro", port: 8080, type: "HTTP", online: true, provider: "CrazyGames" },
  { host: "crazygames.ro", port: 8880, type: "HTTP", online: true, provider: "CrazyGames" },
  { host: "crazygames.ro", port: 2086, type: "HTTP", online: true, provider: "CrazyGames" },
  { host: "crazygames.ro", port: 443, type: "SSL", online: true, provider: "CrazyGames" },
  { host: "crazygames.ro", port: 80, type: "HTTP", online: true, provider: "CrazyGames" },
  // partner-stream.twitter.com
  { host: "partner-stream.twitter.com", port: 8080, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "partner-stream.twitter.com", port: 8880, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "partner-stream.twitter.com", port: 2086, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "partner-stream.twitter.com", port: 443, type: "SSL", online: true, provider: "Twitter/CDN" },
  { host: "partner-stream.twitter.com", port: 80, type: "HTTP", online: true, provider: "Twitter/CDN" },
  // guest-cf.pscp.tv
  { host: "guest-cf.pscp.tv", port: 8080, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "guest-cf.pscp.tv", port: 8880, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "guest-cf.pscp.tv", port: 2086, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "guest-cf.pscp.tv", port: 443, type: "SSL", online: true, provider: "Periscope/Twitter" },
  { host: "guest-cf.pscp.tv", port: 80, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  // dev-guest-cf.pscp.tv
  { host: "dev-guest-cf.pscp.tv", port: 8080, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "dev-guest-cf.pscp.tv", port: 8880, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "dev-guest-cf.pscp.tv", port: 2086, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  { host: "dev-guest-cf.pscp.tv", port: 443, type: "SSL", online: true, provider: "Periscope/Twitter" },
  { host: "dev-guest-cf.pscp.tv", port: 80, type: "HTTP", online: true, provider: "Periscope/Twitter" },
  // 162.159.140.229
  { host: "162.159.140.229", port: 8080, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "162.159.140.229", port: 8880, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "162.159.140.229", port: 2086, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "162.159.140.229", port: 443, type: "SSL", online: true, provider: "Cloudflare Anycast" },
  { host: "162.159.140.229", port: 80, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  // cf.twimg.com
  { host: "cf.twimg.com", port: 8080, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "cf.twimg.com", port: 8880, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "cf.twimg.com", port: 2086, type: "HTTP", online: true, provider: "Twitter/CDN" },
  { host: "cf.twimg.com", port: 443, type: "SSL", online: true, provider: "Twitter/CDN" },
  { host: "cf.twimg.com", port: 80, type: "HTTP", online: true, provider: "Twitter/CDN" },
  // help.twitter.com
  { host: "help.twitter.com", port: 8080, type: "HTTP", online: true, provider: "Twitter" },
  { host: "help.twitter.com", port: 8880, type: "HTTP", online: true, provider: "Twitter" },
  { host: "help.twitter.com", port: 2086, type: "HTTP", online: true, provider: "Twitter" },
  { host: "help.twitter.com", port: 443, type: "SSL", online: true, provider: "Twitter" },
  { host: "help.twitter.com", port: 80, type: "HTTP", online: true, provider: "Twitter" },
  // 172.66.0.227
  { host: "172.66.0.227", port: 8080, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "172.66.0.227", port: 8880, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "172.66.0.227", port: 2086, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  { host: "172.66.0.227", port: 443, type: "SSL", online: true, provider: "Cloudflare Anycast" },
  { host: "172.66.0.227", port: 80, type: "HTTP", online: true, provider: "Cloudflare Anycast" },
  // مزيج المجالات مع video-cf.twimg.com
  { host: "help.twitter.com;tweetdeck.twitter.com;www.twitter.com;analytics.twitter.com;support.twitter.com;video-cf.twimg.com", port: 8080, type: "HTTP", online: true, provider: "Twitter Multi-Domain" },
  { host: "help.twitter.com;tweetdeck.twitter.com;www.twitter.com;analytics.twitter.com;support.twitter.com;video-cf.twimg.com", port: 8880, type: "HTTP", online: true, provider: "Twitter Multi-Domain" },
  { host: "help.twitter.com;tweetdeck.twitter.com;www.twitter.com;analytics.twitter.com;support.twitter.com;video-cf.twimg.com", port: 2086, type: "HTTP", online: true, provider: "Twitter Multi-Domain" },
  { host: "help.twitter.com;tweetdeck.twitter.com;www.twitter.com;analytics.twitter.com;support.twitter.com;video-cf.twimg.com", port: 443, type: "SSL", online: true, provider: "Twitter Multi-Domain" },
  { host: "help.twitter.com;tweetdeck.twitter.com;www.twitter.com;analytics.twitter.com;support.twitter.com;video-cf.twimg.com", port: 80, type: "HTTP", online: true, provider: "Twitter Multi-Domain" },
  // m.jakarie.io
  { host: "m.jakarie.io", port: 8080, type: "HTTP", online: true, provider: "Jakarie" },
  { host: "m.jakarie.io", port: 8880, type: "HTTP", online: true, provider: "Jakarie" },
  { host: "m.jakarie.io", port: 2086, type: "HTTP", online: true, provider: "Jakarie" },
  { host: "m.jakarie.io", port: 443, type: "SSL", online: true, provider: "Jakarie" },
  { host: "m.jakarie.io", port: 80, type: "HTTP", online: true, provider: "Jakarie" },
  // test.cftls.t.co
  { host: "test.cftls.t.co", port: 8080, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 8880, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 2086, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 443, type: "SSL", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 80, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  // cloudapi.snap.com
  { host: "cloudapi.snap.com", port: 8080, type: "HTTP", online: true, provider: "Snap/Cloudflare" },
  { host: "cloudapi.snap.com", port: 8880, type: "HTTP", online: true, provider: "Snap/Cloudflare" },
  { host: "cloudapi.snap.com", port: 2086, type: "HTTP", online: true, provider: "Snap/Cloudflare" },
  { host: "cloudapi.snap.com", port: 443, type: "SSL", online: true, provider: "Snap/Cloudflare" },
  { host: "cloudapi.snap.com", port: 80, type: "HTTP", online: true, provider: "Snap/Cloudflare" },
  // تكرار test.cftls.t.co
  { host: "test.cftls.t.co", port: 8080, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 8880, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 2086, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 443, type: "SSL", online: true, provider: "Twitter/Cloudflare" },
  { host: "test.cftls.t.co", port: 80, type: "HTTP", online: true, provider: "Twitter/Cloudflare" },
];

export const SNI_DATA = [
  { hostname: "googleapis.com" },
  { hostname: "v9x6qb-launches.appsflyersdk.com" },
  { hostname: "content-autofill.googleapis.com" },
  { hostname: "web.instagram.com" },
  { hostname: "help.instagram.com" },
  { hostname: "m.instagram.com" },
  { hostname: "www.instagram.com" },
  { hostname: "api.instagram.com" },
  { hostname: "cdn.instagram.com" },
  { hostname: "static.instagram.com" },
  { hostname: "web.snapchat.com" },
  { hostname: "help.snapchat.com" },
  { hostname: "m.snapchat.com" },
  { hostname: "www.snapchat.com" },
  { hostname: "api.snapchat.com" },
  { hostname: "cdn.snapchat.com" },
  { hostname: "web.facebook.com" },
  { hostname: "help.facebook.com" },
  { hostname: "m.facebook.com" },
  { hostname: "www.facebook.com" },
  { hostname: "api.facebook.com" },
  { hostname: "cdn.facebook.com" },
  { hostname: "static.facebook.com" },
  { hostname: "web.whatsapp.com" },
  { hostname: "m.whatsapp.com" },
  { hostname: "www.whatsapp.com" },
  { hostname: "api.whatsapp.com" },
  { hostname: "cdn.whatsapp.com" },
  { hostname: "web.telegram.org" },
  { hostname: "m.telegram.org" },
  { hostname: "www.telegram.org" },
  { hostname: "api.telegram.org" },
  { hostname: "cdn.telegram.org" },
  { hostname: "www.tiktok.com" },
  { hostname: "m.tiktok.com" },
  { hostname: "api.tiktok.com" },
  { hostname: "cdn.tiktok.com" },
  { hostname: "assets.twitch.tv" },
  { hostname: "www.twitch.tv" },
  { hostname: "m.twitch.tv" },
  { hostname: "api.twitch.tv" },
  { hostname: "cdn.twitch.tv" },
  { hostname: "cdn.discordapp.com" },
  { hostname: "api.discordapp.com" },
  { hostname: "www.discordapp.com" },
  { hostname: "www.twitter.com" },
  { hostname: "api.twitter.com" },
  { hostname: "cdn.twitter.com" },
  { hostname: "web.cloudflare.com" },
  { hostname: "help.cloudflare.com" },
  { hostname: "api.cloudflare.com" },
  { hostname: "cdn.cloudflare.com" },
  { hostname: "googel.com" },
  { hostname: "instagram.com" },
  { hostname: "video.pscp.tv" },
  { hostname: "m.jakarie.io" },
  { hostname: "microsoft.com" },
  { hostname: "web.poe.garena.com" },
  { hostname: "video-cf.twimg.com" },
  { hostname: "ff.garena.com" },
  { hostname: "h.facebook.com" },
  { hostname: "crazygames.ro" },
  { hostname: "abs-cloudflare.twimg.com" },
];

export const BUG_HOSTS = [
  { bug: "web.poe.garena.com", note: "Garena CDN" },
  { bug: "video-cf.twimg.com", note: "Twitter Video CDN" },
  { bug: "ff.garena.com", note: "Garena Free Fire" },
  { bug: "h.facebook.com", note: "Facebook Mobile" },
  { bug: "crazygames.ro", note: "CrazyGames Romania" },
  { bug: "abs-cloudflare.twimg.com", note: "Twitter Cloudflare CDN" },
  { bug: "104.18.37.127", note: "Cloudflare IP (direct)" },
  { bug: "googleapis.com", note: "Google APIs" },
  { bug: "v9x6qb-launches.appsflyersdk.com", note: "AppsFlyer SDK" },
  { bug: "content-autofill.googleapis.com", note: "Google Autofill" },
  { bug: "web.instagram.com", note: "Instagram CDN" },
  { bug: "help.instagram.com", note: "Instagram Help" },
  { bug: "m.instagram.com", note: "Instagram Mobile" },
  { bug: "www.instagram.com", note: "Instagram Main" },
  { bug: "api.instagram.com", note: "Instagram API" },
  { bug: "cdn.instagram.com", note: "Instagram CDN" },
  { bug: "static.instagram.com", note: "Instagram Static" },
  { bug: "web.snapchat.com", note: "Snapchat CDN" },
  { bug: "help.snapchat.com", note: "Snapchat Help" },
  { bug: "m.snapchat.com", note: "Snapchat Mobile" },
  { bug: "www.snapchat.com", note: "Snapchat Main" },
  { bug: "api.snapchat.com", note: "Snapchat API" },
  { bug: "web.facebook.com", note: "Facebook CDN" },
  { bug: "help.facebook.com", note: "Facebook Help" },
  { bug: "m.facebook.com", note: "Facebook Mobile" },
  { bug: "www.facebook.com", note: "Facebook Main" },
  { bug: "api.facebook.com", note: "Facebook API" },
  { bug: "web.whatsapp.com", note: "WhatsApp Web" },
  { bug: "m.whatsapp.com", note: "WhatsApp Mobile" },
  { bug: "www.whatsapp.com", note: "WhatsApp Main" },
  { bug: "api.whatsapp.com", note: "WhatsApp API" },
  { bug: "web.telegram.org", note: "Telegram Web" },
  { bug: "m.telegram.org", note: "Telegram Mobile" },
  { bug: "www.telegram.org", note: "Telegram Main" },
  { bug: "api.telegram.org", note: "Telegram API" },
  { bug: "www.tiktok.com", note: "TikTok Main" },
  { bug: "m.tiktok.com", note: "TikTok Mobile" },
  { bug: "api.tiktok.com", note: "TikTok API" },
  { bug: "assets.twitch.tv", note: "Twitch Assets" },
  { bug: "www.twitch.tv", note: "Twitch Main" },
  { bug: "m.twitch.tv", note: "Twitch Mobile" },
  { bug: "cdn.discordapp.com", note: "Discord CDN" },
  { bug: "api.discordapp.com", note: "Discord API" },
  { bug: "web.cloudflare.com", note: "Cloudflare Web" },
  { bug: "help.cloudflare.com", note: "Cloudflare Help" },
  { bug: "api.cloudflare.com", note: "Cloudflare API" },
];

export const PROVIDERS_DATA = [
  { name: "SSH Ocean", url: "https://sshocean.com", type: "SSH/SSL/WebSocket/V2Ray" },
  { name: "SSH Max", url: "https://sshmax.net", type: "SSH/SSL/WebSocket/DNS" },
  { name: "Hide SSH", url: "https://hidessh.com", type: "SSH/V2Ray/OpenVPN" },
  { name: "VPN Jantit", url: "https://www.vpnjantit.com", type: "SSH/SSL/OpenVPN" },
  { name: "Premium SSH", url: "https://www.premiumssh.com", type: "SSH/SSL" },
  { name: "Fast SSH", url: "https://www.fastssh.com", type: "SSH/SSL/Stunnel" },
  { name: "SSH Kit", url: "https://sshkit.com", type: "SSH/SSL" },
  { name: "SSH 8", url: "https://sshs8.com", type: "SSH/OpenVPN/V2Ray" },
  { name: "NETQ.ME", url: "https://netq.me", type: "V2Ray/VMess/Trojan/VLess/SSH/Wireguard" },
  { name: "NeoSSH", url: "https://neossh.com", type: "SSH/SSL/WebSocket/OpenVPN/V2Ray/WireGuard" },
  { name: "MangoHost", url: "https://mangohost.net/vps/personal-vpn", type: "VPS/VPN/SSH/V2Ray/Xray/Wireguard" },
  { name: "SSH Servers", url: "https://sshservers.com", type: "SSH/TCP/UDP" },
  { name: "OpenTunnel", url: "https://opentunnel.net", type: "V2Ray/Trojan/OpenVPN/WireGuard" },
  { name: "MonthlySSH", url: "https://monthlyssh.net", type: "SSH/WebSocket/OpenVPN/XRay/Wireguard" },
  { name: "CyberSSH", url: "https://cyberssh.com", type: "SSH/SSL/VPN" },
  { name: "SSH Stores", url: "https://www.sshstores.net", type: "SSH/SSL/WebSocket/Xray/OpenVPN/Wireguard" },
  { name: "AkunSSH", url: "https://akunssh.net", type: "SSH/UDP/WebSocket/OpenVPN/V2Ray/Wireguard" },
  { name: "StarSSH", url: "https://starssh.com", type: "SSH/OpenVPN" },
  { name: "RACEVPN", url: "https://www.racevpn.com", type: "VPN/SSH" },
  { name: "NetworkSSH", url: "https://networkssh.com", type: "SSH/VPN" },
  { name: "Fast-SSH", url: "https://fast-ssh.com", type: "SSH/V2Ray/Xray/Trojan/Wireguard/OpenVPN" },
];

export const APPS_DEV = [
  { name: "MT Manager", version: "2.14.5-clone-MOD", url: "https://www.mediafire.com/file/onbo1eedk0tcib1/MT+Manager___vip___@l4chan_2.14.5-clone-MOD-v6-xml-fix-final.apk/file" },
  { name: "NP Manager VIP", version: "v2.3.0", url: "https://t.me/xitsahmx77_0/589", note: "Turn off internet before opening the app." },
];

export const APPS_VPN = [
  { name: "Bee Plus V2ray", version: "85.0.0", url: "https://www.mediafire.com/file/i8u5nsh7dwg2514/Bee+Plus+V2ray_85.0.0.apk/file" },
  { name: "TLS Tunnel", version: "8.1.0", url: "https://www.mediafire.com/file/6eebi3vz0p3ixs6/TLS+Tunnel_8.1.0.apk/file" },
  { name: "Every Proxy Core", version: "0.1.0", url: "https://www.mediafire.com/file/vmus4wyims14533/Every+Proxy+Core_0.1.0.apk/file" },
  { name: "SNI Checker", version: "1.6", url: "https://www.mediafire.com/file/ccmi5jtucdwh72w/SNI+Checker_1.6.apk/file" },
  { name: "Ultra Tunnel (No Ads)", version: "v49", url: "https://www.mediafire.com/file/cqonlwowe96vt54/Ultra___,_,_Tunnel_v49____@l4chan.apk/file" },
  { name: "HTTP RIFFIX77 (No Ads)", version: "6.9.20-RC93", url: "https://www.mediafire.com/file/2fz2u3hr2dnskkk/HTTP+RIFFIX77_6.9.20-RC93.7z/file" },
  { name: "HA Tunnel (No Ads)", version: "v5.2.1", url: "https://www.mediafire.com/file/pgbbw01mzicdam3/H_A_Tunnel_@l4chanx_Crack_Done.apk/file" },
  { name: "Handsome Fast (No Ads)", version: "1.8", url: "https://www.mediafire.com/file/men2k7wok11r0a0/Handsome+Fast_1.8.apk/file" },
  { name: "FNF TUNNEL BD (No Ads)", version: "PrinceBuild35", url: "https://www.mediafire.com/file/hvap7fuhqjzylki/FNF+TUNNEL+BD_PrinceBuild35.apk/file" },
];

export const APPS_EXTRA = [
  { name: "MicroG RE", version: "6.1.4", url: "https://www.mediafire.com/file/9ezac5ho3d0yt86/MicroG+RE_6.1.4.apk/file" },
  { name: "YouTube ReVanced", version: "20.14.43", url: "https://www.mediafire.com/file/ejuoz243u7ye9tm/YouTube+ReVanced_20.14.43.apk/file" },
];

export const VIDEOS = [
  { title: "XitSahmX77 Tutorial - Tunnel Setup", description: "Complete guide to configure tunneling with XitSahmX77 payloads.", link: "https://youtu.be/s08vB70Hd20", device: "All", embed: "https://www.youtube.com/embed/s08vB70Hd20" },
];

export const ARTICLES_DATA = [
  {
    id: 1,
    title: "Understanding HTTP vs HTTPS: Ports 80 and 443 Explained",
    category: "Technical",
    date: "2026-07-23",
    content: `
### What is HTTP?

HTTP (Hypertext Transfer Protocol) is the foundation of data communication on the World Wide Web...

[محتوى المقال كامل كما هو]
`,
  },
  {
    id: 2,
    title: "Payload Types: HTTP vs HTTPS and Their Differences",
    category: "Technical",
    date: "2026-07-23",
    content: `
### What Are Payloads?

In the context of tunneling and networking, a payload is a specially crafted HTTP or HTTPS request...

[محتوى المقال كامل كما هو]
`,
  },
  {
    id: 3,
    title: "Why ISPs Cannot Fully Stop Tunneling: A Technical Analysis",
    category: "Security",
    date: "2026-07-23",
    content: `
### The ISP Challenge

Internet Service Providers face significant challenges when trying to block tunneling and VPN traffic...

[محتوى المقال كامل كما هو]
`,
  },
  {
    id: 4,
    title: "How to Set Up a Temporary Test VPS (For Educational Purposes Only)",
    category: "Tutorial",
    date: "2026-07-23",
    content: `
### ⚠️ IMPORTANT LEGAL & PLATFORM WARNING

**GitHub Codespaces is NOT a VPS.** Using it for VPN/proxy/tunneling hosting **violates GitHub's Terms of Service**...

[محتوى المقال كامل كما هو]
`,
  },
];

export const CLOUDFLARE_IPS = {
  ipv4: [
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22"
  ],
  ipv6: [
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32"
  ]
};

export const SOCIAL = {
  telegram: "https://t.me/l4chanx",
  github: "https://github.com/XitSahmX77",
  youtube: "https://youtube.com/@xitsahmx77",
  whatsapp: "https://whatsapp.com/channel/0029VbCI0nX1t90cKSM4342C",
  discord: "https://discord.gg/Wdj496pMT",
  instagram: "https://www.instagram.com/xitsahmx77",
};
